services:
  postgres:
    image: postgres
    container_name: postgres-metalcalc
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: metalcalc
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: